language: python
sudo: false
matrix:
    include:
        - python: 2.7
        - python: 3.4
        - python: 3.6
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests, e.g. python setup.py test
script:
  nosetests unittests.py --with-coverage --cover-package=diophantine
after_success:
  coveralls
